feat: example refactor
nervosnetwork/ckb-sdk-java pull request #548
Opened 2022-05-10 07:32 UTC by fjchen7

2022-06-03 02:43 UTC, quake requested changes

2022-06-09 08:34 UTC, fjchen7 commented
The related documentation change will made in other PR.

2022-06-12 06:26 UTC, quake commented on example/src/main/java/org/nervos/ckb/example/MintSudtExample.java
> +public class MintSudtExample {
suggest to rename `IssueSudtExample` since we are using `SudtTransactionBuilder.TransactionType.ISSUE`.

2022-06-12 06:27 UTC, quake approved these changes

2022-06-12 07:43 UTC, merged